#!/usr/bin/env python3
"""Generate ``_includes/research-jsonld.html`` (ScholarlyArticle JSON-LD).

Emits one ``<script type="application/ld+json">`` block with an ``@graph``:
a compact Person node (``@id`` = ``https://mauricio-romero.com/#person``, so
the per-article author references resolve on the research page itself) plus
one ``ScholarlyArticle`` per paper returned by :func:`parse_papers`.

Stdlib-only by design (no third-party imports). The output file is committed,
like ``llms.txt`` — re-run this script after **any** edit to ``research.qmd``
(the ``add-publication`` skill does this automatically).

Field rules (empty fields are omitted, never emitted as ""):
- author: Mauricio as an ``@id`` reference, then one plain Person per coauthor
  (no @id/sameAs for coauthors — no verified identifiers for them).
- datePublished: prose year, else BibTeX year, else omitted.
- isPartOf Periodical: only for published sections (Publications / Articles /
  Comments) — working/resting-paper status lines are not journal names.
- identifier/url: DOI URL preferred; the title's journal link as fallback.
- encoding: the PDF, plus the Markdown twin when it exists on disk.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from paper_metadata import REPO_ROOT, SITE_URL, parse_papers  # noqa: E402

OUT_PATH = REPO_ROOT / "_includes" / "research-jsonld.html"
PERSON_ID = f"{SITE_URL}/#person"

PERSON_NODE = {
    "@id": PERSON_ID,
    "@type": "Person",
    "name": "Mauricio Romero",
    "url": f"{SITE_URL}/",
    "sameAs": [
        "https://orcid.org/0000-0003-4652-593X",
        "https://scholar.google.com/citations?user=BD8UfDoAAAAJ",
    ],
}

PUBLISHED_SECTION_WORDS = ("publications", "articles", "comments")


def _article(p) -> tuple[dict, list[str]]:
    """Build one ScholarlyArticle node; return (node, omitted-field labels)."""
    omitted = []

    node = {
        "@type": "ScholarlyArticle",
        "headline": p.title,
        "name": p.title,
        "author": [{"@id": PERSON_ID}]
        + [{"@type": "Person", "name": name} for name in p.coauthors],
    }

    year = p.year or p.bibtex_year
    if year:
        node["datePublished"] = year
    else:
        omitted.append("datePublished")

    section = p.section.lower()
    if p.venue and any(w in section for w in PUBLISHED_SECTION_WORDS):
        node["isPartOf"] = {"@type": "Periodical", "name": p.venue}
    else:
        omitted.append("isPartOf")

    if p.doi:
        doi_url = f"https://doi.org/{p.doi}"
        node["identifier"] = doi_url
        node["url"] = doi_url
    elif p.journal_url:
        node["url"] = p.journal_url
        omitted.append("identifier")
    else:
        omitted.append("identifier")
        omitted.append("url")

    if p.abstract:
        node["abstract"] = p.abstract
    else:
        omitted.append("abstract")

    encoding = [
        {
            "@type": "MediaObject",
            "encodingFormat": "application/pdf",
            "contentUrl": p.pdf_url,
        }
    ]
    if p.md_path.exists():
        encoding.append(
            {
                "@type": "MediaObject",
                "encodingFormat": "text/markdown",
                "contentUrl": p.md_url,
            }
        )
    else:
        omitted.append("encoding:markdown-twin")
    node["encoding"] = encoding

    return node, omitted


def main() -> int:
    papers = parse_papers()
    graph = [PERSON_NODE]
    n_url = 0

    for p in papers:
        node, omitted = _article(p)
        graph.append(node)
        if "url" in node:
            n_url += 1
        if omitted:
            print(f"  omitted [{', '.join(omitted)}]  {p.title[:60]}", file=sys.stderr)

    payload = {"@context": "https://schema.org", "@graph": graph}
    html = (
        "<!-- Generated by tools/gen-research-jsonld.py - do not hand-edit.\n"
        "     Re-run after any research.qmd change (the add-publication skill does). -->\n"
        '<script type="application/ld+json">\n'
        + json.dumps(payload, indent=2, ensure_ascii=False)
        + "\n</script>\n"
    )
    OUT_PATH.write_text(html, encoding="utf-8")

    n_doi = sum(1 for p in papers if p.doi)
    print(
        f"Wrote {OUT_PATH} ({len(papers)} articles + 1 Person node; "
        f"url populated for {n_url}, DOIs {n_doi}).",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
